# Generated by Django 4.1.6 on 2023-03-27 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='age',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='DateDeNaissance',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
